"""fix: restore api key security columns

Revision ID: 9ec43e84b2af
Revises: 23f1f82ab452
Create Date: 2026-04-06 23:33:16.430744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec43e84b2af'
down_revision = '23f1f82ab452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('api_key_encrypted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_encrypted', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
