"""fix(auth): add has_used_trial flag to user model

Revision ID: ad8406056168
Revises: 9ec43e84b2af
Create Date: 2026-04-06 23:42:14.548070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8406056168'
down_revision = '9ec43e84b2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_used_trial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_used_trial')

    # ### end Alembic commands ###
