"""add hashed and encrypted api key columns to project

Revision ID: ce9ad347c277
Revises: ad8406056168
Create Date: 2026-04-07 00:42:14.137551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9ad347c277'
down_revision = 'ad8406056168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key_encrypted', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('api_key_encrypted')

    # ### end Alembic commands ###
